// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
	"github.com/moumou/server/biz/dao"
	"github.com/moumou/server/biz/service/page"
	"github.com/moumou/server/biz/service/router"
	"github.com/moumou/server/biz/service/user"
	"github.com/moumou/server/pkgs/database"
)

// Injectors from wire.go:

func InitService() (*Service, error) {
	db, err := database.NewMysqlGorm()
	if err != nil {
		return nil, err
	}
	daoDao := dao.NewDao(db)
	service := user.NewUserService(daoDao)
	routerService := router.NewRouterService(daoDao)
	pageService := page.NewPageService(db)
	serviceService := NewService(service, routerService, pageService, daoDao)
	return serviceService, nil
}

// wire.go:

var serviceSet = wire.NewSet(
	NewService, user.NewUserService, router.NewRouterService, page.NewPageService, dao.NewDao, database.NewMysqlGorm,
)
