// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
	"github.com/moumou/server/biz/service/user"
	"github.com/moumou/server/framework/database"
)

// Injectors from wire.go:

func InitService() (*Service, error) {
	db, err := database.NewMysqlGorm()
	if err != nil {
		return nil, err
	}
	service := user.NewUserService(db)
	serviceService := NewService(service)
	return serviceService, nil
}

// wire.go:

var serviceSet = wire.NewSet(NewService, user.NewUserService, database.NewMysqlGorm)
