// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/google/wire"
	"github.com/moumou/server/biz/service/page"
	"github.com/moumou/server/biz/service/sys_router"
	"github.com/moumou/server/biz/service/sys_user"
	"github.com/moumou/server/framework/database"
)

// Injectors from wire.go:

func InitService() (*Service, error) {
	db, err := database.NewMysqlGorm()
	if err != nil {
		return nil, err
	}
	service := sys_user.NewSysUserService(db)
	sys_routerService := sys_router.NewRouterService(db)
	pageService := page.NewPageService(db)
	serviceService := NewService(service, sys_routerService, pageService)
	return serviceService, nil
}

// wire.go:

var serviceSet = wire.NewSet(
	NewService, sys_user.NewSysUserService, sys_router.NewRouterService, page.NewPageService, database.NewMysqlGorm,
)
