// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.27.1
// source: router.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRouterHandlerCreateRouter = "/moumou.server.api.RouterHandler/CreateRouter"
const OperationRouterHandlerGetRouterInfo = "/moumou.server.api.RouterHandler/GetRouterInfo"
const OperationRouterHandlerGetRouterList = "/moumou.server.api.RouterHandler/GetRouterList"

type RouterHandlerHTTPServer interface {
	CreateRouter(context.Context, *CreateRouterRequest) (*CreateRouterResponse, error)
	GetRouterInfo(context.Context, *GetRouterInfoRequest) (*GetRouterInfoResponse, error)
	GetRouterList(context.Context, *GetRouterListRequest) (*GetRouterListResponse, error)
}

func RegisterRouterHandlerHTTPServer(s *http.Server, srv RouterHandlerHTTPServer) {
	r := s.Route("/")
	r.POST("/router/create", _RouterHandler_CreateRouter0_HTTP_Handler(srv))
	r.POST("/router/list", _RouterHandler_GetRouterList0_HTTP_Handler(srv))
	r.POST("/router/info", _RouterHandler_GetRouterInfo0_HTTP_Handler(srv))
}

func _RouterHandler_CreateRouter0_HTTP_Handler(srv RouterHandlerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRouterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouterHandlerCreateRouter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRouter(ctx, req.(*CreateRouterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRouterResponse)
		return ctx.Result(200, reply)
	}
}

func _RouterHandler_GetRouterList0_HTTP_Handler(srv RouterHandlerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRouterListRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouterHandlerGetRouterList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRouterList(ctx, req.(*GetRouterListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRouterListResponse)
		return ctx.Result(200, reply)
	}
}

func _RouterHandler_GetRouterInfo0_HTTP_Handler(srv RouterHandlerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRouterInfoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouterHandlerGetRouterInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRouterInfo(ctx, req.(*GetRouterInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRouterInfoResponse)
		return ctx.Result(200, reply)
	}
}

type RouterHandlerHTTPClient interface {
	CreateRouter(ctx context.Context, req *CreateRouterRequest, opts ...http.CallOption) (rsp *CreateRouterResponse, err error)
	GetRouterInfo(ctx context.Context, req *GetRouterInfoRequest, opts ...http.CallOption) (rsp *GetRouterInfoResponse, err error)
	GetRouterList(ctx context.Context, req *GetRouterListRequest, opts ...http.CallOption) (rsp *GetRouterListResponse, err error)
}

type RouterHandlerHTTPClientImpl struct {
	cc *http.Client
}

func NewRouterHandlerHTTPClient(client *http.Client) RouterHandlerHTTPClient {
	return &RouterHandlerHTTPClientImpl{client}
}

func (c *RouterHandlerHTTPClientImpl) CreateRouter(ctx context.Context, in *CreateRouterRequest, opts ...http.CallOption) (*CreateRouterResponse, error) {
	var out CreateRouterResponse
	pattern := "/router/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRouterHandlerCreateRouter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RouterHandlerHTTPClientImpl) GetRouterInfo(ctx context.Context, in *GetRouterInfoRequest, opts ...http.CallOption) (*GetRouterInfoResponse, error) {
	var out GetRouterInfoResponse
	pattern := "/router/info"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRouterHandlerGetRouterInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RouterHandlerHTTPClientImpl) GetRouterList(ctx context.Context, in *GetRouterListRequest, opts ...http.CallOption) (*GetRouterListResponse, error) {
	var out GetRouterListResponse
	pattern := "/router/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRouterHandlerGetRouterList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
