server:
  host: "${APP_SERVER_HOST}"
  port: "${APP_SERVER_PORT}"
  timeout: "${APP_SERVER_TIMEOUT}"

security:
  jwt_key: "${APP_SECURITY_JWTKEY}"

database:
  user: "${APP_DATABASE_USER}"
  password: "${APP_DATABASE_PASSWORD}"
  db_name: "${APP_DATABASE_DBNAME}"
  addr: "${APP_DATABASE_ADDR}"
